### ISSUE TITLE
DH exchange

### ISSUE THREAD

**Issue by klnmi97** [danzatt/PV204_project#2]
- Investigate DH/ECDH
- Implement simple DH

**Comment by danzatt** [comment]
Example elliptic curve DH available in host_app in [`dh-test`](https://github.com/danzatt/PV204_project/tree/dh-test) branch.

**Comment by klnmi97** [comment]
Almost done, but I cannot send more than 255 bytes in the apdu data

**Comment by klnmi97** [comment]
ECDH implemented
